spring:
  application:
    name: talent-acquisition
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    hibernate:
      ddl-auto: create-drop
#  flyway:
#    locations: classpath:/db/migration
#    schemas: employees
#    baselineOnMigrate: true
#    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Demo
    username: postgres
    password: pbrqXhy*fNb6
logging:
  level:
    org:
      springframework:
        security: debug